apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nestjs-k8s
  namespace: poc
  labels:
    app: nestjs-k8s
spec: 
  selector:
    matchLabels:
      app: nestjs-k8s
  replicas: 3
  template:
    metadata: 
      labels:
        app: nestjs-k8s
    spec: 
      containers:
       - name: nestjs-k8s
         image: chinoyerem/nestjs-k8s
        #  here downwards is used for aws cloud deployment
         ports:
         - containerPort: 3000
         env:
         - name: POD_NAME
           valueFrom:
              fieldRef:
                 fieldPath: metadate.name
         - name : POD_NAMESPACE
           valueFrom:
              fieldRef:
                fieldPath: metadate.namespace
         - name: POD_IP
           valueFrom:
              fieldRef:
                fieldPath: status.podIP
         #  helps us to manage a pod resources here is for k8s cluster
         resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

